# Site settings
title: Rezepte etc
description: > #
  Eine Liste an Rezepten
baseurl: "/rezepte" # the subpath of your site, e.g. /blog/
url: "http://afdia.github.io" # the base hostname & protocol for your site
github_username:  afdia

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-minimal
